---
OUTPUT_DIR: "/home/haeata/.glioblastoma_portal/scans"
PROGRESS_LOG: "/home/haeata/.glioblastoma_portal/progress.log"
FAILURE_LOG: "/home/haeata/.glioblastoma_portal/failure.log"
# Increasing chunk size will speed things up but will increase ram usage
CHUNK_SIZE: 16384
# Concurrent downloads does nothing currently - not implemented
CONCURRENT_DOWNLOADS: 4
LOGFILE: "/home/haeata/.glioblastoma_portal/download.log"
LOGLEVEL: "DEBUG"


